import json
from datetime import datetime
from web3 import Web3
import streamlit as st


# Update this with your Alchemy API key
ALCHEMY_URL = "https://eth-sepolia.g.alchemy.com/v2/YOUR-API-KEY"

# Use the smart contract address from your deployment
# This is the contract I deployed on Sepolia for testing - replace with your own if needed
CONTRACT_ADDRESS = "0x00ff0dfbDFe4719016a4Bcc1ef2E31132bC21147"

# Load the Smart Contract ABI - this is the contract metadata generated by the Solidity compiler
with open('Crowdfunding.json', 'r') as f:
    contract_json = json.load(f)
    CONTRACT_ABI = contract_json['abi']

# Initialize Web3 and target smart contract instance
w3 = Web3(Web3.HTTPProvider(ALCHEMY_URL))
contract = w3.eth.contract(address=CONTRACT_ADDRESS, abi=CONTRACT_ABI)

st.set_page_config(page_title="Crowdfunding DApp", layout="wide")
st.title("🚀 Crowdfunding Campaign Dashboard")

tier_names = ["None", "🥉 Bronze", "🥈 Silver", "🥇 Gold"]

if 'private_key' not in st.session_state:
    st.session_state.private_key = ''

# Sidebar for wallet connection and account info
with st.sidebar:
    st.header("🔑 Wallet Connection")
    private_key = st.text_input("Private Key", type="password", value=st.session_state.private_key)
    if private_key:
        st.session_state.private_key = private_key
        account = w3.eth.account.from_key(private_key)
        st.success(f"Connected: {account.address[:6]}...{account.address[-4:]}")
        balance = w3.eth.get_balance(account.address)
        st.info(f"Balance: {w3.from_wei(balance, 'ether'):.4f} ETH")
    else:
        st.warning("Enter private key to interact")

owner = contract.functions.owner().call()
goal = w3.from_wei(contract.functions.goal().call(), 'ether')
deadline_timestamp = contract.functions.deadline().call()
total_funds = w3.from_wei(contract.functions.totalFunds().call(), 'ether')
contributors_count = contract.functions.getContributorsCount().call()

deadline_dt = datetime.fromtimestamp(deadline_timestamp)
time_remaining = deadline_dt - datetime.now()
is_active = time_remaining.total_seconds() > 0
is_successful = total_funds >= goal

col1, col2, col3, col4 = st.columns(4)
with col1:
    st.metric("Goal", f"{goal:.5f} ETH")
with col2:
    st.metric("Raised", f"{total_funds:.5f} ETH")
with col3:
    st.metric("Progress", f"{(total_funds/goal*100):.2f}%")
with col4:
    st.metric("Contributors", contributors_count)

st.progress(float(min(total_funds / goal, 1.0)))

col_a, col_b = st.columns(2)
with col_a:
    if is_active:
        st.success(f"⏰ Ends: {deadline_dt.strftime('%Y-%m-%d %H:%M')}")
    elif is_successful:
        st.success("✅ Campaign Successful!")
    else:
        st.error("❌ Campaign Failed")
        
with col_b:
    if is_active:
        days = time_remaining.days
        hours = time_remaining.seconds // 3600
        st.info(f"⏳ {days}d {hours}h remaining")

st.divider()

if private_key:
    account = w3.eth.account.from_key(private_key)
    is_owner = account.address.lower() == owner.lower()
    
    my_contribution = w3.from_wei(contract.functions.contributions(account.address).call(), 'ether')
    my_tier = contract.functions.rewardTiers(account.address).call()
    
    st.subheader("Your Contribution")
    col1, col2 = st.columns(2)
    with col1:
        st.metric("Amount", f"{my_contribution:.4f} ETH")
    with col2:
        st.metric("Reward Tier", tier_names[my_tier])
    
    if my_tier > 0:
        if st.button("🎁 Get Reward Form"):
            reward_url = contract.functions.getRewardFormUrl().call()
            st.success(f"Reward Form: {reward_url}")
    
    st.divider()
    
    if is_active:
        st.subheader("💰 Make Contribution")
        amount = st.number_input("Amount (ETH)", min_value=0.001, step=0.001)
        
        if st.button("Contribute", type="primary"):
            tx = contract.functions.contribute().build_transaction({
                'from': account.address,
                'value': w3.to_wei(amount, 'ether'),
                'gas': 300000,
                'gasPrice': w3.eth.gas_price,
                'nonce': w3.eth.get_transaction_count(account.address),
            })
            signed = w3.eth.account.sign_transaction(tx, private_key)
            tx_hash = w3.eth.send_raw_transaction(signed.raw_transaction)
            st.success(f"Transaction sent: {tx_hash.hex()}")
            st.info("Refresh page after block validation to see updates")
    
    if is_owner:
        st.divider()
        st.subheader("👑 Owner Controls")
        
        col1, col2, col3 = st.columns(3)
        
        with col1:
            if not is_active and is_successful:
                if st.button("💸 Withdraw Funds"):
                    tx = contract.functions.withdraw().build_transaction({
                        'from': account.address,
                        'gas': 300000,
                        'gasPrice': w3.eth.gas_price,
                        'nonce': w3.eth.get_transaction_count(account.address),
                    })
                    signed = w3.eth.account.sign_transaction(tx, private_key)
                    tx_hash = w3.eth.send_raw_transaction(signed.raw_transaction)
                    st.success(f"Transaction sent: {tx_hash.hex()}")
        
        with col2:
            if not is_active and not is_successful:
                if st.button("🔄 Refund All"):
                    tx = contract.functions.refundAll().build_transaction({
                        'from': account.address,
                        'gas': 500000,
                        'gasPrice': w3.eth.gas_price,
                        'nonce': w3.eth.get_transaction_count(account.address),
                    })
                    signed = w3.eth.account.sign_transaction(tx, private_key)
                    tx_hash = w3.eth.send_raw_transaction(signed.raw_transaction)
                    st.success(f"Transaction sent: {tx_hash.hex()}")
        
        with col3:
            reward_url = st.text_input("Reward Form URL")
            if st.button("Set Reward URL") and reward_url:
                tx = contract.functions.setRewardFormUrl(reward_url).build_transaction({
                    'from': account.address,
                    'gas': 300000,
                    'gasPrice': w3.eth.gas_price,
                    'nonce': w3.eth.get_transaction_count(account.address),
                })
                signed = w3.eth.account.sign_transaction(tx, private_key)
                tx_hash = w3.eth.send_raw_transaction(signed.raw_transaction)
                st.success(f"URL set: {tx_hash.hex()}")

st.divider()
st.subheader("🏆 Top Contributors")

addresses, amounts = contract.functions.getTopContributors(5).call()
for i, (addr, amt) in enumerate(zip(addresses, amounts)):
    if addr != "0x0000000000000000000000000000000000000000":
        eth_amount = w3.from_wei(amt, 'ether')
        tier = contract.functions.rewardTiers(addr).call()
        st.write(f"{i+1}. {addr[:6]}...{addr[-4:]} - {eth_amount:.4f} ETH {tier_names[tier]}")